---
mappings:
- alias: "/NHS/Cancer Late Presentation Likelihood Modelling Internal Transforms/cancer-late-datasets/interim-datasets/IP_features"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.b927c07a-1679-402a-9b98-f564cc2f4998"
- alias: "/NHS/Cancer Late Presentation Likelihood Modelling Internal Transforms/cancer-late-datasets/interim-datasets/combined_comorbidities"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.3f34bfba-9440-4b7b-9d54-59be8a52bb0e"
- alias: "/NHS/Cancer Late Presentation Likelihood Modelling Internal Transforms/cancer-late-datasets/interim-datasets/ecds_snomed_icd10_mapping"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.cb2b417b-98d0-4d94-b492-6380de39776e"
- alias: "/NHS/Cancer Late Presentation Likelihood Modelling Internal Transforms/cancer-late-datasets/interim-datasets/outcome_variable"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.30a5ce42-d7ca-4152-8ce3-7573fc39bfe2"
- alias: "/NHS/Cancer Late Presentation Likelihood Modelling Internal Transforms/cancer-late-datasets/interim-datasets/patient_features_expanded"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.8e0a3764-c7b6-4e43-80f0-84139cf8ff6c"
- alias: "/NHS/Cancer Late Presentation Likelihood Modelling Internal Transforms/cancer-late-datasets/interim-datasets/stroke_diagnosis"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e6df5039-fd19-4b34-8dfd-85042cc5b24a"
- alias: "/NHS/Cancer Late Presentation Likelihood Modelling Internal Transforms/cancer-late-datasets/interim-datasets/stroke_outcome_variable"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.f72e9326-395c-40f3-a56d-6d073b6f53a3"
- alias: "/NHS/Cancer Late Presentation Likelihood Modelling Internal Transforms/cancer-late-datasets/target-datasets/IDs_to_remove"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.b31e0565-7803-4729-8805-961db7279f07"
- alias: "/NHS/Cancer Late Presentation Likelihood Modelling Internal Transforms/cancer-late-datasets/target-datasets/patient_features_subset_stroke"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.16af93e4-536c-4d4e-83b6-2df608128fa6"
- alias: "/NHS/Cancer Late Presentation Likelihood Modelling Internal Transforms/cancer-late-datasets/target-datasets/stroke_IDs_to_remove"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.bf97af2b-f0a0-408c-89bd-418517d879ce"
- alias: "ri.foundry.main.dataset.00a2c97d-1499-4b4e-8cad-3af7cba8a599"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.00a2c97d-1499-4b4e-8cad-3af7cba8a599"
- alias: "ri.foundry.main.dataset.0cc8c784-f957-47b5-9844-a69d7eee0f6a"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.0cc8c784-f957-47b5-9844-a69d7eee0f6a"
- alias: "ri.foundry.main.dataset.10e87cda-7bbc-4d0c-a8b3-c2559b832dd3"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.10e87cda-7bbc-4d0c-a8b3-c2559b832dd3"
- alias: "ri.foundry.main.dataset.16af93e4-536c-4d4e-83b6-2df608128fa6"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.16af93e4-536c-4d4e-83b6-2df608128fa6"
- alias: "ri.foundry.main.dataset.195dd683-e55b-450e-abeb-5f00de85ad78"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.195dd683-e55b-450e-abeb-5f00de85ad78"
- alias: "ri.foundry.main.dataset.2341ae73-65bc-405f-a1c7-e644da6e0255"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.2341ae73-65bc-405f-a1c7-e644da6e0255"
- alias: "ri.foundry.main.dataset.2a792e6d-170e-4f42-8093-2db225060034"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.2a792e6d-170e-4f42-8093-2db225060034"
- alias: "ri.foundry.main.dataset.30a5ce42-d7ca-4152-8ce3-7573fc39bfe2"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.30a5ce42-d7ca-4152-8ce3-7573fc39bfe2"
- alias: "ri.foundry.main.dataset.36644003-34c3-43d0-bace-751b3e071ea3"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.36644003-34c3-43d0-bace-751b3e071ea3"
- alias: "ri.foundry.main.dataset.3a0dfe4b-67de-4001-87eb-e43405df76d3"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.3a0dfe4b-67de-4001-87eb-e43405df76d3"
- alias: "ri.foundry.main.dataset.3b5c090a-bad0-4568-9163-d37a41c748e1"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.3b5c090a-bad0-4568-9163-d37a41c748e1"
- alias: "ri.foundry.main.dataset.3f34bfba-9440-4b7b-9d54-59be8a52bb0e"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.3f34bfba-9440-4b7b-9d54-59be8a52bb0e"
- alias: "ri.foundry.main.dataset.4725c357-f053-498d-9113-127bde5edc55"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.4725c357-f053-498d-9113-127bde5edc55"
- alias: "ri.foundry.main.dataset.56032935-c25c-4262-8bd0-a8de9091ef85"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.56032935-c25c-4262-8bd0-a8de9091ef85"
- alias: "ri.foundry.main.dataset.57b3da18-8389-4083-bb74-499bb3208f04"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.57b3da18-8389-4083-bb74-499bb3208f04"
- alias: "ri.foundry.main.dataset.5ce08265-84ab-4d90-a38a-df31e47ecb47"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.5ce08265-84ab-4d90-a38a-df31e47ecb47"
- alias: "ri.foundry.main.dataset.7525a5d9-610c-4927-8cc4-fa12d3a17c4c"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.7525a5d9-610c-4927-8cc4-fa12d3a17c4c"
- alias: "ri.foundry.main.dataset.793b42d6-f24d-4cca-b500-abc319dd5162"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.793b42d6-f24d-4cca-b500-abc319dd5162"
- alias: "ri.foundry.main.dataset.8e0a3764-c7b6-4e43-80f0-84139cf8ff6c"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.8e0a3764-c7b6-4e43-80f0-84139cf8ff6c"
- alias: "ri.foundry.main.dataset.a3dfadbc-b022-4d88-98c2-8ee3392beed1"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a3dfadbc-b022-4d88-98c2-8ee3392beed1"
- alias: "ri.foundry.main.dataset.a91f6452-b404-4ce3-b48a-7cafae278b7a"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a91f6452-b404-4ce3-b48a-7cafae278b7a"
- alias: "ri.foundry.main.dataset.b243b273-4b66-4326-a37b-8bc060c8bdf6"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.b243b273-4b66-4326-a37b-8bc060c8bdf6"
- alias: "ri.foundry.main.dataset.b2a84252-8ae1-4f7c-9948-c7e00afe36a8"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.b2a84252-8ae1-4f7c-9948-c7e00afe36a8"
- alias: "ri.foundry.main.dataset.b31e0565-7803-4729-8805-961db7279f07"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.b31e0565-7803-4729-8805-961db7279f07"
- alias: "ri.foundry.main.dataset.bc82a106-d0b2-4837-9d46-1aabcb4db0d2"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.bc82a106-d0b2-4837-9d46-1aabcb4db0d2"
- alias: "ri.foundry.main.dataset.bf97af2b-f0a0-408c-89bd-418517d879ce"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.bf97af2b-f0a0-408c-89bd-418517d879ce"
- alias: "ri.foundry.main.dataset.c12f6390-def6-4fa4-bb51-1e70e3ac1c20"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.c12f6390-def6-4fa4-bb51-1e70e3ac1c20"
- alias: "ri.foundry.main.dataset.c3f3cfb4-0e3b-44e1-a1c4-a10c0c463ae2"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.c3f3cfb4-0e3b-44e1-a1c4-a10c0c463ae2"
- alias: "ri.foundry.main.dataset.cb2b417b-98d0-4d94-b492-6380de39776e"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.cb2b417b-98d0-4d94-b492-6380de39776e"
- alias: "ri.foundry.main.dataset.cf9cd953-d9c4-486f-9130-607c252ed8e1"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.cf9cd953-d9c4-486f-9130-607c252ed8e1"
- alias: "ri.foundry.main.dataset.e3a5741d-6cb5-4b64-8d3b-0be26b1b6e62"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e3a5741d-6cb5-4b64-8d3b-0be26b1b6e62"
- alias: "ri.foundry.main.dataset.e5ca6fce-6839-4b1d-801c-81e2e976c5bd"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e5ca6fce-6839-4b1d-801c-81e2e976c5bd"
- alias: "ri.foundry.main.dataset.e6df5039-fd19-4b34-8dfd-85042cc5b24a"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e6df5039-fd19-4b34-8dfd-85042cc5b24a"
- alias: "ri.foundry.main.dataset.e6f4ebc3-9175-4bd4-9ab0-550b011abde8"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e6f4ebc3-9175-4bd4-9ab0-550b011abde8"
- alias: "ri.foundry.main.dataset.f0e0629f-e190-40fa-a7c3-a95ce8d2fe6a"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.f0e0629f-e190-40fa-a7c3-a95ce8d2fe6a"
- alias: "ri.foundry.main.dataset.f72e9326-395c-40f3-a56d-6d073b6f53a3"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.f72e9326-395c-40f3-a56d-6d073b6f53a3"
- alias: "ri.foundry.main.dataset.f84bc6f9-fffe-4c38-afa4-911c5a515a08"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.f84bc6f9-fffe-4c38-afa4-911c5a515a08"
- alias: "ri.foundry.main.dataset.fa19d9b5-066a-4d57-aef4-59d2cda4a8ac"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.fa19d9b5-066a-4d57-aef4-59d2cda4a8ac"
- alias: "ri.foundry.main.dataset.fe042d45-d081-4221-ae22-b930587fb500"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.fe042d45-d081-4221-ae22-b930587fb500"
