---
mappings:
- alias: "/NHS/cancer-late-presentation/cancer-late-datasets/interim-datasets/111_pathways_features"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a3dfadbc-b022-4d88-98c2-8ee3392beed1"
- alias: "/NHS/cancer-late-presentation/cancer-late-datasets/interim-datasets/comorbidity_features"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.7525a5d9-610c-4927-8cc4-fa12d3a17c4c"
- alias: "/NHS/cancer-late-presentation/cancer-late-datasets/interim-datasets/inpatient_comorbidities"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.fe042d45-d081-4221-ae22-b930587fb500"
- alias: "/NHS/cancer-late-presentation/cancer-late-datasets/interim-datasets/patient_health_record_features"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.195dd683-e55b-450e-abeb-5f00de85ad78"
- alias: "ri.foundry.main.dataset.0cc8c784-f957-47b5-9844-a69d7eee0f6a"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.0cc8c784-f957-47b5-9844-a69d7eee0f6a"
- alias: "ri.foundry.main.dataset.195dd683-e55b-450e-abeb-5f00de85ad78"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.195dd683-e55b-450e-abeb-5f00de85ad78"
- alias: "ri.foundry.main.dataset.36644003-34c3-43d0-bace-751b3e071ea3"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.36644003-34c3-43d0-bace-751b3e071ea3"
- alias: "ri.foundry.main.dataset.3b5c090a-bad0-4568-9163-d37a41c748e1"
  modes:
  - "BUILD"
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.3b5c090a-bad0-4568-9163-d37a41c748e1"
- alias: "ri.foundry.main.dataset.4725c357-f053-498d-9113-127bde5edc55"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.4725c357-f053-498d-9113-127bde5edc55"
- alias: "ri.foundry.main.dataset.793b42d6-f24d-4cca-b500-abc319dd5162"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.793b42d6-f24d-4cca-b500-abc319dd5162"
- alias: "ri.foundry.main.dataset.a3dfadbc-b022-4d88-98c2-8ee3392beed1"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a3dfadbc-b022-4d88-98c2-8ee3392beed1"
- alias: "ri.foundry.main.dataset.a91f6452-b404-4ce3-b48a-7cafae278b7a"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.a91f6452-b404-4ce3-b48a-7cafae278b7a"
- alias: "ri.foundry.main.dataset.b2a84252-8ae1-4f7c-9948-c7e00afe36a8"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.b2a84252-8ae1-4f7c-9948-c7e00afe36a8"
- alias: "ri.foundry.main.dataset.bc82a106-d0b2-4837-9d46-1aabcb4db0d2"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.bc82a106-d0b2-4837-9d46-1aabcb4db0d2"
- alias: "ri.foundry.main.dataset.e6f4ebc3-9175-4bd4-9ab0-550b011abde8"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.e6f4ebc3-9175-4bd4-9ab0-550b011abde8"
- alias: "ri.foundry.main.dataset.f0e0629f-e190-40fa-a7c3-a95ce8d2fe6a"
  modes:
  - "BUILD"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.f0e0629f-e190-40fa-a7c3-a95ce8d2fe6a"
- alias: "ri.foundry.main.dataset.fe042d45-d081-4221-ae22-b930587fb500"
  modes:
  - "READ"
  path: "/deprecated-field"
  rid: "ri.foundry.main.dataset.fe042d45-d081-4221-ae22-b930587fb500"
